### ISSUE TITLE
.ENV variables don't work

### ISSUE THREAD

**Issue by ProfGrosvenor** [scenery-io/create-script#13]
Variables in the .env file don't seem to be visible to the src script. To repo have TEST='something' in the .env and console.log(TEST) in the main script and it will break. 

Weirdly it doesn't just return undefined, it breaks the script

error logs
[10:06:58.319 error   ] ReferenceError: TEST is not defined at <anonymous>:161:13
[10:06:58.320 error   ] undefined:161: ReferenceError: TEST is not defined:<br>console.log(TEST);<br>------------^
[10:06:58.424 error   ] JavaScript Error. See the JavaScript Console for more details.

**Comment by Klustre** [comment]
Thanks! Let me look into this when I can.

> Weirdly it doesn't just return undefined, it breaks the script

That's because the variable doesn't exist, because it's not being replaced at compile time. So it's not declared instead of having an `undefined` value.

**Comment by Klustre** [comment]
Make sure you run `npm run dev` again after changing the `.env` file. If that doesn't solve it, can you create an example repo that reproduces the issue?

**Comment by Klustre** [comment]
Rerunning `npm run dev` solved the issue. The `.env` file is not watched for changes.
